version: 2.20.2
services:
  db:
    image: postgres
    container_name: postgres-container
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
  api:
    build: "./backend"
    container_name: spring-container
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
  web:
    build: "./frontend"
    container_name: react-container
    restart: always
    ports:
      - "5000:3000"
    depends_on:
      - api